"""
RAG Engine for Diagram Generation using LangChain and Mistral AI
- Document loading: PyPDFLoader (with pdfplumber fallback)
- Chunking: RecursiveCharacterTextSplitter
- VectorStore: FAISS with MistralAIEmbeddings (mistral-embed)
- LLM: ChatMistralAI (mistral-large-latest)
- Multi-diagram support & Mermaid code sanitizer
"""

import os
import re
from typing import List, Dict, Any, Optional
from dotenv import load_dotenv

from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import FAISS
from langchain_mistralai import MistralAIEmbeddings, ChatMistralAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser


load_dotenv()


def sanitize_mermaid_code(code: str) -> str:
    """
    Cleans and validates Mermaid code generated by LLMs to prevent browser rendering errors.
    - Strips markdown code blocks
    - Ensures valid diagram type prefix
    - Quotes bracketed node labels with special characters
    """
    if not code:
        return "flowchart TD\n    A[No diagram generated]"

    # Remove markdown code fences
    cleaned = code.strip()
    if "```mermaid" in cleaned:
        cleaned = cleaned.split("```mermaid")[1].split("```")[0].strip()
    elif "```" in cleaned:
        cleaned = cleaned.replace("```", "").strip()

    lines = cleaned.splitlines()
    filtered_lines = []
    
    valid_starters = (
        "flowchart", "graph", "sequenceDiagram", "stateDiagram",
        "stateDiagram-v2", "classDiagram", "erDiagram", "gantt", "mindmap"
    )

    header_found = False
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        
        # Check if line is a diagram header
        if any(stripped.startswith(prefix) for prefix in valid_starters):
            header_found = True
            filtered_lines.append(stripped)
            continue
        
        if header_found:
            # Auto-quote square bracket labels with unsafe characters: [Some Text (Extra)] -> ["Some Text (Extra)"]
            # Only if not already enclosed in quotes
            def quote_square_brackets(m):
                content = m.group(1)
                if not (content.startswith('"') and content.endswith('"')) and any(c in content for c in "():;,/\\{}[]"):
                    return f'["{content}"]'
                return f'[{content}]'
            
            line_sanitized = re.sub(r'\[([^\]]+)\]', quote_square_brackets, line)
            filtered_lines.append(line_sanitized)

    if not header_found or not filtered_lines:
        # Fallback if LLM forgot header
        return "flowchart TD\n" + "\n".join(filtered_lines if filtered_lines else ["    A[Start] --> B[End]"])

    return "\n".join(filtered_lines)


class DiagramRAGEngine:
    """End-to-End RAG engine for analyzing documents and generating diagrams."""

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("MISTRAL_API_KEY")
        if not self.api_key:
            raise ValueError("MISTRAL_API_KEY is required. Please set it in environment variables.")

        # Initialize Embeddings & LLM
        self.embeddings = MistralAIEmbeddings(
            model="mistral-embed",
            api_key=self.api_key
        )
        self.llm = ChatMistralAI(
            model="mistral-large-latest",
            api_key=self.api_key,
            temperature=0.1
        )
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=900,
            chunk_overlap=120,
            separators=["\n\n", "\n", ". ", " ", ""]
        )

    def load_pdf(self, pdf_path: str) -> List[Document]:
        """Loads and splits PDF using PyPDFLoader with fallback."""
        if not os.path.exists(pdf_path):
            raise FileNotFoundError(f"PDF not found: {pdf_path}")

        try:
            loader = PyPDFLoader(pdf_path)
            docs = loader.load()
            if docs and any(doc.page_content.strip() for doc in docs):
                return docs
        except Exception as e:
            print(f"PyPDFLoader warning: {e}, attempting pdfplumber extraction...")

        # Fallback using pdfplumber
        import pdfplumber
        docs = []
        with pdfplumber.open(pdf_path) as pdf:
            for i, page in enumerate(pdf.pages):
                text = page.extract_text() or ""
                if text.strip():
                    docs.append(Document(
                        page_content=text,
                        metadata={"source": pdf_path, "page": i + 1}
                    ))
        
        if not docs:
            raise ValueError("Could not extract any readable text from the provided PDF.")
        return docs

    def load_text(self, text: str, source_name: str = "raw_text") -> List[Document]:
        """Wraps raw text into LangChain Document."""
        if not text or not text.strip():
            raise ValueError("Input text cannot be empty.")
        return [Document(page_content=text.strip(), metadata={"source": source_name, "page": 1})]

    def build_vector_store(self, documents: List[Document]) -> FAISS:
        """Splits documents and creates an in-memory FAISS vector store."""
        chunks = self.text_splitter.split_documents(documents)
        if not chunks:
            raise ValueError("No text chunks could be generated from document.")
        vectorstore = FAISS.from_documents(chunks, self.embeddings)
        return vectorstore

    def retrieve_context(self, vectorstore: FAISS, query: Optional[str] = None, k: int = 5) -> List[Document]:
        """
        Retrieves top-k relevant chunks based on custom query or automated general architecture query.
        """
        search_query = query if (query and query.strip()) else "system architecture process workflow sequence components interactions overview"
        retriever = vectorstore.as_retriever(search_kwargs={"k": k})
        retrieved_docs = retriever.invoke(search_query)
        return retrieved_docs

    def generate_summary(self, context_text: str, query: Optional[str] = None) -> str:
        """Generates a clean, concise plain-text summary of the system architecture."""
        summary_prompt = ChatPromptTemplate.from_template(
            """Analyze the provided technical context and produce a direct, concise summary in 2 to 4 clear sentences.

Context:
{context}

{query_instruction}

STRICT RULES:
- Output ONLY plain text (NO markdown headers, NO tables, NO bullets, NO code blocks).
- Clearly explain what the system does, its key components, and how data/requests flow end-to-end.
- Keep it concise, natural, and easy to read.

Summary:"""
        )

        query_instruction = f"Focus specifically on answering: '{query}'" if (query and query.strip()) else ""

        chain = summary_prompt | self.llm | StrOutputParser()
        summary = chain.invoke({
            "context": context_text,
            "query_instruction": query_instruction
        })
        
        # Clean any accidental markdown artifacts
        clean_summary = summary.strip().replace('```markdown', '').replace('```', '').strip()
        return clean_summary

    def generate_mermaid_diagram(
        self,
        context_text: str,
        summary: str,
        diagram_type: str = "auto",
        query: Optional[str] = None
    ) -> str:
        """Generates clean, validated Mermaid diagram code from context and summary."""

        # Determine diagram type guidance
        type_instructions = {
            "flowchart_td": "Create a top-down flowchart starting with `flowchart TD`.",
            "flowchart_lr": "Create a left-to-right flowchart starting with `flowchart LR`.",
            "sequence": "Create a sequence diagram starting with `sequenceDiagram` detailing interactions between participants/actors.",
            "state": "Create a state diagram starting with `stateDiagram-v2` detailing states, transitions, and conditions.",
            "class": "Create a class or entity relationship diagram starting with `classDiagram`."
        }

        specific_instruction = type_instructions.get(
            diagram_type,
            "Choose the most appropriate Mermaid diagram type (e.g. `flowchart TD`, `flowchart LR`, or `sequenceDiagram`). Start with the diagram declaration on line 1."
        )

        user_query_note = f"\nUSER SPECIFIC FOCUS: {query}\n" if (query and query.strip()) else ""

        diagram_prompt = ChatPromptTemplate.from_template(
            """You are a senior diagrams architect. Generate a high-quality, syntactically flawless Mermaid.js diagram representing the system/process described below.

CONTEXT:
{context}

SUMMARY:
{summary}
{user_query_note}

DIAGRAM TYPE INSTRUCTION:
{specific_instruction}

STRICT SYNTAX & QUALITY RULES:
1. Output ONLY executable Mermaid code. Do NOT wrap in markdown explanation or conversational text.
2. The very first line MUST be the diagram type declaration (e.g. `flowchart TD`, `sequenceDiagram`, `stateDiagram-v2`).
3. For Flowcharts:
   - Use meaningful, clean node IDs (e.g. `User`, `AuthService`, `DB`, `Step1`).
   - ALWAYS quote node text that contains special characters, parentheses, commas, or colons (e.g. `A["Process Request (v2)"]`, `B{{"Is Authenticated?"}}`).
   - Use standard connection arrows: `-->`, `-->|label|`, `-.->`, `==>`.
4. Keep the diagram concise, readable, and visually well-structured (between 8 and 20 nodes).
5. Ensure every referenced node in connections is properly defined.

Mermaid Code:"""
        )

        chain = diagram_prompt | self.llm | StrOutputParser()
        raw_mermaid = chain.invoke({
            "context": context_text,
            "summary": summary,
            "user_query_note": user_query_note,
            "specific_instruction": specific_instruction
        })

        sanitized_mermaid = sanitize_mermaid_code(raw_mermaid)
        return sanitized_mermaid

    def process(
        self,
        pdf_path: Optional[str] = None,
        text: Optional[str] = None,
        query: Optional[str] = None,
        diagram_type: str = "auto",
        k_chunks: int = 5
    ) -> Dict[str, Any]:
        """
        Executes the full RAG pipeline:
        1. Load document (PDF or text)
        2. Chunk & index into FAISS
        3. Retrieve most relevant chunks (RAG)
        4. Generate structured summary
        5. Generate and sanitize Mermaid diagram
        """
        if pdf_path:
            raw_docs = self.load_pdf(pdf_path)
            source_type = "pdf"
        elif text:
            raw_docs = self.load_text(text)
            source_type = "text"
        else:
            raise ValueError("Either pdf_path or text must be provided.")

        full_content = "\n\n".join(doc.page_content for doc in raw_docs)
        
        # Step 2: Chunk & Build Vector Store
        chunks = self.text_splitter.split_documents(raw_docs)
        vectorstore = FAISS.from_documents(chunks, self.embeddings)

        # Step 3: Retrieve relevant chunks
        retrieved_docs = self.retrieve_context(vectorstore, query=query, k=min(k_chunks, len(chunks)))
        context_text = "\n\n---\n\n".join(
            f"[Source: Chunk {i+1} (Page {doc.metadata.get('page', 1)})]\n{doc.page_content}"
            for i, doc in enumerate(retrieved_docs)
        )

        # Step 4: Generate Summary
        summary = self.generate_summary(context_text, query=query)

        # Step 5: Generate Mermaid Diagram
        mermaid_code = self.generate_mermaid_diagram(
            context_text=context_text,
            summary=summary,
            diagram_type=diagram_type,
            query=query
        )

        return {
            "success": True,
            "source_type": source_type,
            "mermaid_code": mermaid_code,
            "summary": summary,
            "query": query,
            "diagram_type": diagram_type,
            "retrieved_chunks": [
                {
                    "id": i + 1,
                    "page": doc.metadata.get("page", 1),
                    "content": doc.page_content
                }
                for i, doc in enumerate(retrieved_docs)
            ],
            "stats": {
                "total_pages": len(raw_docs) if source_type == "pdf" else 1,
                "total_chunks": len(chunks),
                "retrieved_chunks_count": len(retrieved_docs),
                "original_characters": len(full_content),
                "summary_characters": len(summary),
                "mermaid_characters": len(mermaid_code)
            }
        }
